include: package:coca_lints/analysis_options.yaml
formatter:
  trailing_commas: preserve
linter:
  rules:
    unawaited_futures: true
analyzer:
  errors:
    sort_constructors_first: ignore
    prefer_const_constructors_in_immutables: ignore
    invalid_use_of_visible_for_testing_member: error
    unawaited_futures: warning
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
