/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/cocahonka/hecate/frontend/golang_piv_bindings */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "go_piv_bindings.go"

 #include <stdlib.h>
 #include <stdint.h>
 typedef int64_t go_piv_bindings_handle_t;
 typedef struct {
   int32_t code;
   const char* msg;
 } go_piv_bindings_status_t;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern go_piv_bindings_status_t go_piv_bindings_device_open(go_piv_bindings_handle_t* out);
extern go_piv_bindings_status_t go_piv_bindings_device_close(go_piv_bindings_handle_t handle);
extern go_piv_bindings_status_t go_piv_bindings_device_authenticate(go_piv_bindings_handle_t handle, char* pin);
extern go_piv_bindings_status_t go_piv_bindings_piv_status(go_piv_bindings_handle_t handle, int32_t* has9c, int32_t* has9d, char** pk9c, char** pk9d);
extern go_piv_bindings_status_t go_piv_bindings_sign_challenge(go_piv_bindings_handle_t handle, char* challenge, char** sig, char* pinOpt);
extern go_piv_bindings_status_t go_piv_bindings_wrap_aes_for_recipients(char** recipients, int32_t n, char*** encKeys, int32_t* encN);
extern go_piv_bindings_status_t go_piv_bindings_encrypt_message(go_piv_bindings_handle_t handle, char* encAES, char* pt, char* aad, char** envelope);
extern go_piv_bindings_status_t go_piv_bindings_decrypt_message(go_piv_bindings_handle_t handle, char* encAES, char* envelope, char** pt);
extern go_piv_bindings_status_t go_piv_bindings_piv_slot9c_policy(go_piv_bindings_handle_t handle, int32_t* pinPolicy, int32_t* touchPolicy);
extern void go_piv_bindings_free_string(char* s);
extern void go_piv_bindings_free_string_array(char** arr, int32_t n);

#ifdef __cplusplus
}
#endif
