events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/v1/user/ {
            proxy_pass http://user-service:8082/user/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/chats/ {
            proxy_pass http://chat-service:8083/api/v1/chats/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/messages/ {
            proxy_pass http://message-service:8084/api/v1/messages/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
