// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockchallengeSaver is an autogenerated mock type for the challengeSaver type
type MockchallengeSaver struct {
	mock.Mock
}

type MockchallengeSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockchallengeSaver) EXPECT() *MockchallengeSaver_Expecter {
	return &MockchallengeSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, nickname, challenge, ttl
func (_m *MockchallengeSaver) Save(ctx context.Context, nickname string, challenge string, ttl time.Duration) error {
	ret := _m.Called(ctx, nickname, challenge, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, nickname, challenge, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockchallengeSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockchallengeSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - challenge string
//   - ttl time.Duration
func (_e *MockchallengeSaver_Expecter) Save(ctx interface{}, nickname interface{}, challenge interface{}, ttl interface{}) *MockchallengeSaver_Save_Call {
	return &MockchallengeSaver_Save_Call{Call: _e.mock.On("Save", ctx, nickname, challenge, ttl)}
}

func (_c *MockchallengeSaver_Save_Call) Run(run func(ctx context.Context, nickname string, challenge string, ttl time.Duration)) *MockchallengeSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockchallengeSaver_Save_Call) Return(_a0 error) *MockchallengeSaver_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockchallengeSaver_Save_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockchallengeSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockchallengeSaver creates a new instance of MockchallengeSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockchallengeSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockchallengeSaver {
	mock := &MockchallengeSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
