// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockchallengeManager is an autogenerated mock type for the challengeManager type
type MockchallengeManager struct {
	mock.Mock
}

type MockchallengeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockchallengeManager) EXPECT() *MockchallengeManager_Expecter {
	return &MockchallengeManager_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, nickname
func (_m *MockchallengeManager) Delete(ctx context.Context, nickname string) error {
	ret := _m.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, nickname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockchallengeManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockchallengeManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockchallengeManager_Expecter) Delete(ctx interface{}, nickname interface{}) *MockchallengeManager_Delete_Call {
	return &MockchallengeManager_Delete_Call{Call: _e.mock.On("Delete", ctx, nickname)}
}

func (_c *MockchallengeManager_Delete_Call) Run(run func(ctx context.Context, nickname string)) *MockchallengeManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockchallengeManager_Delete_Call) Return(_a0 error) *MockchallengeManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockchallengeManager_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockchallengeManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx, nickname
func (_m *MockchallengeManager) Load(ctx context.Context, nickname string) (string, error) {
	ret := _m.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, nickname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, nickname)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockchallengeManager_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockchallengeManager_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockchallengeManager_Expecter) Load(ctx interface{}, nickname interface{}) *MockchallengeManager_Load_Call {
	return &MockchallengeManager_Load_Call{Call: _e.mock.On("Load", ctx, nickname)}
}

func (_c *MockchallengeManager_Load_Call) Run(run func(ctx context.Context, nickname string)) *MockchallengeManager_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockchallengeManager_Load_Call) Return(_a0 string, _a1 error) *MockchallengeManager_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockchallengeManager_Load_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockchallengeManager_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, nickname, challenge, ttl
func (_m *MockchallengeManager) Save(ctx context.Context, nickname string, challenge string, ttl time.Duration) error {
	ret := _m.Called(ctx, nickname, challenge, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, nickname, challenge, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockchallengeManager_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockchallengeManager_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - challenge string
//   - ttl time.Duration
func (_e *MockchallengeManager_Expecter) Save(ctx interface{}, nickname interface{}, challenge interface{}, ttl interface{}) *MockchallengeManager_Save_Call {
	return &MockchallengeManager_Save_Call{Call: _e.mock.On("Save", ctx, nickname, challenge, ttl)}
}

func (_c *MockchallengeManager_Save_Call) Run(run func(ctx context.Context, nickname string, challenge string, ttl time.Duration)) *MockchallengeManager_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockchallengeManager_Save_Call) Return(_a0 error) *MockchallengeManager_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockchallengeManager_Save_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockchallengeManager_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockchallengeManager creates a new instance of MockchallengeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockchallengeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockchallengeManager {
	mock := &MockchallengeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
