// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMocknicknameChecker creates a new instance of MocknicknameChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocknicknameChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocknicknameChecker {
	mock := &MocknicknameChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocknicknameChecker is an autogenerated mock type for the nicknameChecker type
type MocknicknameChecker struct {
	mock.Mock
}

type MocknicknameChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MocknicknameChecker) EXPECT() *MocknicknameChecker_Expecter {
	return &MocknicknameChecker_Expecter{mock: &_m.Mock}
}

// IsExists provides a mock function for the type MocknicknameChecker
func (_mock *MocknicknameChecker) IsExists(ctx context.Context, nickname string) (bool, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocknicknameChecker_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type MocknicknameChecker_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MocknicknameChecker_Expecter) IsExists(ctx interface{}, nickname interface{}) *MocknicknameChecker_IsExists_Call {
	return &MocknicknameChecker_IsExists_Call{Call: _e.mock.On("IsExists", ctx, nickname)}
}

func (_c *MocknicknameChecker_IsExists_Call) Run(run func(ctx context.Context, nickname string)) *MocknicknameChecker_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocknicknameChecker_IsExists_Call) Return(b bool, err error) *MocknicknameChecker_IsExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MocknicknameChecker_IsExists_Call) RunAndReturn(run func(ctx context.Context, nickname string) (bool, error)) *MocknicknameChecker_IsExists_Call {
	_c.Call.Return(run)
	return _c
}
