// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRefreshTokenManager is an autogenerated mock type for the RefreshTokenManager type
type MockRefreshTokenManager struct {
	mock.Mock
}

type MockRefreshTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenManager) EXPECT() *MockRefreshTokenManager_Expecter {
	return &MockRefreshTokenManager_Expecter{mock: &_m.Mock}
}

// DeleteRefreshToken provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenManager) DeleteRefreshToken(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenManager_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockRefreshTokenManager_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenManager_Expecter) DeleteRefreshToken(ctx interface{}, userID interface{}) *MockRefreshTokenManager_DeleteRefreshToken_Call {
	return &MockRefreshTokenManager_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, userID)}
}

func (_c *MockRefreshTokenManager_DeleteRefreshToken_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenManager_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenManager_DeleteRefreshToken_Call) Return(_a0 error) *MockRefreshTokenManager_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenManager_DeleteRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenManager_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenManager) GetRefreshToken(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenManager_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockRefreshTokenManager_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenManager_Expecter) GetRefreshToken(ctx interface{}, userID interface{}) *MockRefreshTokenManager_GetRefreshToken_Call {
	return &MockRefreshTokenManager_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, userID)}
}

func (_c *MockRefreshTokenManager_GetRefreshToken_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenManager_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenManager_GetRefreshToken_Call) Return(_a0 string, _a1 error) *MockRefreshTokenManager_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenManager_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRefreshTokenManager_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: ctx, userID, refreshToken, ttl
func (_m *MockRefreshTokenManager) SaveRefreshToken(ctx context.Context, userID string, refreshToken string, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, refreshToken, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, refreshToken, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenManager_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockRefreshTokenManager_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
//   - ttl time.Duration
func (_e *MockRefreshTokenManager_Expecter) SaveRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}, ttl interface{}) *MockRefreshTokenManager_SaveRefreshToken_Call {
	return &MockRefreshTokenManager_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, userID, refreshToken, ttl)}
}

func (_c *MockRefreshTokenManager_SaveRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string, ttl time.Duration)) *MockRefreshTokenManager_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRefreshTokenManager_SaveRefreshToken_Call) Return(_a0 error) *MockRefreshTokenManager_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenManager_SaveRefreshToken_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockRefreshTokenManager_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenManager creates a new instance of MockRefreshTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenManager {
	mock := &MockRefreshTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
