// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/cocahonka/hecate/backend/user_service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *MockTokenGenerator) Generate(user domain.User) (string, string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(domain.User) (string, string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.User) string); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(domain.User) error); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user domain.User
func (_e *MockTokenGenerator_Expecter) Generate(user interface{}) *MockTokenGenerator_Generate_Call {
	return &MockTokenGenerator_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *MockTokenGenerator_Generate_Call) Run(run func(user domain.User)) *MockTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.User))
	})
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) Return(accessToken string, refreshToken string, err error) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockTokenGenerator_Generate_Call) RunAndReturn(run func(domain.User) (string, string, error)) *MockTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
