// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cocahonka/hecate/backend/user_service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, nickname
func (_m *MockUserProvider) Get(ctx context.Context, nickname string) (*domain.User, error) {
	ret := _m.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, nickname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, nickname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockUserProvider_Expecter) Get(ctx interface{}, nickname interface{}) *MockUserProvider_Get_Call {
	return &MockUserProvider_Get_Call{Call: _e.mock.On("Get", ctx, nickname)}
}

func (_c *MockUserProvider_Get_Call) Run(run func(ctx context.Context, nickname string)) *MockUserProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserProvider_Get_Call) Return(_a0 *domain.User, _a1 error) *MockUserProvider_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProvider_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
