// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cocahonka/hecate/backend/user_service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserProviderByID is an autogenerated mock type for the UserProviderByID type
type MockUserProviderByID struct {
	mock.Mock
}

type MockUserProviderByID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProviderByID) EXPECT() *MockUserProviderByID_Expecter {
	return &MockUserProviderByID_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *MockUserProviderByID) GetByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserProviderByID_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserProviderByID_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserProviderByID_Expecter) GetByID(ctx interface{}, userID interface{}) *MockUserProviderByID_GetByID_Call {
	return &MockUserProviderByID_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *MockUserProviderByID_GetByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserProviderByID_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserProviderByID_GetByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserProviderByID_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserProviderByID_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserProviderByID_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProviderByID creates a new instance of MockUserProviderByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProviderByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProviderByID {
	mock := &MockUserProviderByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
