// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserSaver
func (_mock *MockUserSaver) Create(ctx context.Context, nickname string, pub9c string, pub9d string) error {
	ret := _mock.Called(ctx, nickname, pub9c, pub9d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, nickname, pub9c, pub9d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserSaver_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserSaver_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - pub9c string
//   - pub9d string
func (_e *MockUserSaver_Expecter) Create(ctx interface{}, nickname interface{}, pub9c interface{}, pub9d interface{}) *MockUserSaver_Create_Call {
	return &MockUserSaver_Create_Call{Call: _e.mock.On("Create", ctx, nickname, pub9c, pub9d)}
}

func (_c *MockUserSaver_Create_Call) Run(run func(ctx context.Context, nickname string, pub9c string, pub9d string)) *MockUserSaver_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserSaver_Create_Call) Return(err error) *MockUserSaver_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserSaver_Create_Call) RunAndReturn(run func(ctx context.Context, nickname string, pub9c string, pub9d string) error) *MockUserSaver_Create_Call {
	_c.Call.Return(run)
	return _c
}
