// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLoginManager is an autogenerated mock type for the LoginManager type
type MockLoginManager struct {
	mock.Mock
}

type MockLoginManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginManager) EXPECT() *MockLoginManager_Expecter {
	return &MockLoginManager_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: ctx, nickname
func (_m *MockLoginManager) Init(ctx context.Context, nickname string) (string, error) {
	ret := _m.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, nickname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, nickname)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginManager_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockLoginManager_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockLoginManager_Expecter) Init(ctx interface{}, nickname interface{}) *MockLoginManager_Init_Call {
	return &MockLoginManager_Init_Call{Call: _e.mock.On("Init", ctx, nickname)}
}

func (_c *MockLoginManager_Init_Call) Run(run func(ctx context.Context, nickname string)) *MockLoginManager_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoginManager_Init_Call) Return(_a0 string, _a1 error) *MockLoginManager_Init_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginManager_Init_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockLoginManager_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken, nickname
func (_m *MockLoginManager) Refresh(ctx context.Context, refreshToken string, nickname *string) (string, string, error) {
	ret := _m.Called(ctx, refreshToken, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) (string, string, error)); ok {
		return rf(ctx, refreshToken, nickname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) string); ok {
		r0 = rf(ctx, refreshToken, nickname)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) string); ok {
		r1 = rf(ctx, refreshToken, nickname)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *string) error); ok {
		r2 = rf(ctx, refreshToken, nickname)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLoginManager_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockLoginManager_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - nickname *string
func (_e *MockLoginManager_Expecter) Refresh(ctx interface{}, refreshToken interface{}, nickname interface{}) *MockLoginManager_Refresh_Call {
	return &MockLoginManager_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken, nickname)}
}

func (_c *MockLoginManager_Refresh_Call) Run(run func(ctx context.Context, refreshToken string, nickname *string)) *MockLoginManager_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockLoginManager_Refresh_Call) Return(accessToken string, newRefreshToken string, err error) *MockLoginManager_Refresh_Call {
	_c.Call.Return(accessToken, newRefreshToken, err)
	return _c
}

func (_c *MockLoginManager_Refresh_Call) RunAndReturn(run func(context.Context, string, *string) (string, string, error)) *MockLoginManager_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, nickname, signature
func (_m *MockLoginManager) Verify(ctx context.Context, nickname string, signature string) (string, string, error) {
	ret := _m.Called(ctx, nickname, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, nickname, signature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, nickname, signature)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, nickname, signature)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, nickname, signature)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLoginManager_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockLoginManager_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - signature string
func (_e *MockLoginManager_Expecter) Verify(ctx interface{}, nickname interface{}, signature interface{}) *MockLoginManager_Verify_Call {
	return &MockLoginManager_Verify_Call{Call: _e.mock.On("Verify", ctx, nickname, signature)}
}

func (_c *MockLoginManager_Verify_Call) Run(run func(ctx context.Context, nickname string, signature string)) *MockLoginManager_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLoginManager_Verify_Call) Return(accessToken string, refreshToken string, err error) *MockLoginManager_Verify_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockLoginManager_Verify_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *MockLoginManager_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginManager creates a new instance of MockLoginManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginManager {
	mock := &MockLoginManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
