// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRegisterManager creates a new instance of MockRegisterManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterManager {
	mock := &MockRegisterManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegisterManager is an autogenerated mock type for the RegisterManager type
type MockRegisterManager struct {
	mock.Mock
}

type MockRegisterManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterManager) EXPECT() *MockRegisterManager_Expecter {
	return &MockRegisterManager_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockRegisterManager
func (_mock *MockRegisterManager) Init(ctx context.Context, nickname string) (string, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegisterManager_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockRegisterManager_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockRegisterManager_Expecter) Init(ctx interface{}, nickname interface{}) *MockRegisterManager_Init_Call {
	return &MockRegisterManager_Init_Call{Call: _e.mock.On("Init", ctx, nickname)}
}

func (_c *MockRegisterManager_Init_Call) Run(run func(ctx context.Context, nickname string)) *MockRegisterManager_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegisterManager_Init_Call) Return(s string, err error) *MockRegisterManager_Init_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRegisterManager_Init_Call) RunAndReturn(run func(ctx context.Context, nickname string) (string, error)) *MockRegisterManager_Init_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAndComplete provides a mock function for the type MockRegisterManager
func (_mock *MockRegisterManager) VerifyAndComplete(ctx context.Context, nickname string, signedChallengeBase64 string, pub9c string, pub9d string) error {
	ret := _mock.Called(ctx, nickname, signedChallengeBase64, pub9c, pub9d)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, nickname, signedChallengeBase64, pub9c, pub9d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegisterManager_VerifyAndComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAndComplete'
type MockRegisterManager_VerifyAndComplete_Call struct {
	*mock.Call
}

// VerifyAndComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - signedChallengeBase64 string
//   - pub9c string
//   - pub9d string
func (_e *MockRegisterManager_Expecter) VerifyAndComplete(ctx interface{}, nickname interface{}, signedChallengeBase64 interface{}, pub9c interface{}, pub9d interface{}) *MockRegisterManager_VerifyAndComplete_Call {
	return &MockRegisterManager_VerifyAndComplete_Call{Call: _e.mock.On("VerifyAndComplete", ctx, nickname, signedChallengeBase64, pub9c, pub9d)}
}

func (_c *MockRegisterManager_VerifyAndComplete_Call) Run(run func(ctx context.Context, nickname string, signedChallengeBase64 string, pub9c string, pub9d string)) *MockRegisterManager_VerifyAndComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRegisterManager_VerifyAndComplete_Call) Return(err error) *MockRegisterManager_VerifyAndComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegisterManager_VerifyAndComplete_Call) RunAndReturn(run func(ctx context.Context, nickname string, signedChallengeBase64 string, pub9c string, pub9d string) error) *MockRegisterManager_VerifyAndComplete_Call {
	_c.Call.Return(run)
	return _c
}
