// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cocahonka/hecate/backend/user_service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserManager is an autogenerated mock type for the UserManager type
type MockUserManager struct {
	mock.Mock
}

type MockUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManager) EXPECT() *MockUserManager_Expecter {
	return &MockUserManager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, nickname
func (_m *MockUserManager) Get(ctx context.Context, nickname string) (*domain.User, error) {
	ret := _m.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, nickname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, nickname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockUserManager_Expecter) Get(ctx interface{}, nickname interface{}) *MockUserManager_Get_Call {
	return &MockUserManager_Get_Call{Call: _e.mock.On("Get", ctx, nickname)}
}

func (_c *MockUserManager_Get_Call) Run(run func(ctx context.Context, nickname string)) *MockUserManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserManager_Get_Call) Return(_a0 *domain.User, _a1 error) *MockUserManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *MockUserManager) GetByID(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserManager_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserManager_Expecter) GetByID(ctx interface{}, userID interface{}) *MockUserManager_GetByID_Call {
	return &MockUserManager_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *MockUserManager_GetByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserManager_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserManager_GetByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserManager_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserManager_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManager creates a new instance of MockUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManager {
	mock := &MockUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
