// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChatClient is an autogenerated mock type for the ChatClient type
type MockChatClient struct {
	mock.Mock
}

type MockChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatClient) EXPECT() *MockChatClient_Expecter {
	return &MockChatClient_Expecter{mock: &_m.Mock}
}

// CheckMembership provides a mock function with given fields: ctx, chatID, token
func (_m *MockChatClient) CheckMembership(ctx context.Context, chatID uuid.UUID, token string) (bool, error) {
	ret := _m.Called(ctx, chatID, token)

	if len(ret) == 0 {
		panic("no return value specified for CheckMembership")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, chatID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, chatID, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, chatID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatClient_CheckMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMembership'
type MockChatClient_CheckMembership_Call struct {
	*mock.Call
}

// CheckMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - token string
func (_e *MockChatClient_Expecter) CheckMembership(ctx interface{}, chatID interface{}, token interface{}) *MockChatClient_CheckMembership_Call {
	return &MockChatClient_CheckMembership_Call{Call: _e.mock.On("CheckMembership", ctx, chatID, token)}
}

func (_c *MockChatClient_CheckMembership_Call) Run(run func(ctx context.Context, chatID uuid.UUID, token string)) *MockChatClient_CheckMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockChatClient_CheckMembership_Call) Return(_a0 bool, _a1 error) *MockChatClient_CheckMembership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatClient_CheckMembership_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockChatClient_CheckMembership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatClient creates a new instance of MockChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatClient {
	mock := &MockChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
