// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cocahonka/hecate/backend/message_service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMessageService is an autogenerated mock type for the MessageService type
type MockMessageService struct {
	mock.Mock
}

type MockMessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageService) EXPECT() *MockMessageService_Expecter {
	return &MockMessageService_Expecter{mock: &_m.Mock}
}

// GetHistory provides a mock function with given fields: ctx, userID, chatID, limit, offset, token
func (_m *MockMessageService) GetHistory(ctx context.Context, userID uuid.UUID, chatID uuid.UUID, limit int, offset int, token string) ([]*domain.Message, error) {
	ret := _m.Called(ctx, userID, chatID, limit, offset, token)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, string) ([]*domain.Message, error)); ok {
		return rf(ctx, userID, chatID, limit, offset, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, string) []*domain.Message); ok {
		r0 = rf(ctx, userID, chatID, limit, offset, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int, string) error); ok {
		r1 = rf(ctx, userID, chatID, limit, offset, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageService_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockMessageService_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - chatID uuid.UUID
//   - limit int
//   - offset int
//   - token string
func (_e *MockMessageService_Expecter) GetHistory(ctx interface{}, userID interface{}, chatID interface{}, limit interface{}, offset interface{}, token interface{}) *MockMessageService_GetHistory_Call {
	return &MockMessageService_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, userID, chatID, limit, offset, token)}
}

func (_c *MockMessageService_GetHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID, chatID uuid.UUID, limit int, offset int, token string)) *MockMessageService_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int), args[5].(string))
	})
	return _c
}

func (_c *MockMessageService_GetHistory_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageService_GetHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageService_GetHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int, string) ([]*domain.Message, error)) *MockMessageService_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, senderID, chatID, payload, token
func (_m *MockMessageService) SendMessage(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, payload string, token string) (*domain.Message, error) {
	ret := _m.Called(ctx, senderID, chatID, payload, token)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (*domain.Message, error)); ok {
		return rf(ctx, senderID, chatID, payload, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) *domain.Message); ok {
		r0 = rf(ctx, senderID, chatID, payload, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, senderID, chatID, payload, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessageService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - chatID uuid.UUID
//   - payload string
//   - token string
func (_e *MockMessageService_Expecter) SendMessage(ctx interface{}, senderID interface{}, chatID interface{}, payload interface{}, token interface{}) *MockMessageService_SendMessage_Call {
	return &MockMessageService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, senderID, chatID, payload, token)}
}

func (_c *MockMessageService_SendMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, chatID uuid.UUID, payload string, token string)) *MockMessageService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockMessageService_SendMessage_Call) Return(_a0 *domain.Message, _a1 error) *MockMessageService_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageService_SendMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (*domain.Message, error)) *MockMessageService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageService creates a new instance of MockMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageService {
	mock := &MockMessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
