// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cocahonka/hecate/backend/message_service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, message
func (_m *MockMessageRepository) Create(ctx context.Context, message *domain.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message *domain.Message
func (_e *MockMessageRepository_Expecter) Create(ctx interface{}, message interface{}) *MockMessageRepository_Create_Call {
	return &MockMessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *MockMessageRepository_Create_Call) Run(run func(ctx context.Context, message *domain.Message)) *MockMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MockMessageRepository_Create_Call) Return(_a0 error) *MockMessageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Message) error) *MockMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChatID provides a mock function with given fields: ctx, chatID, limit, offset
func (_m *MockMessageRepository) GetByChatID(ctx context.Context, chatID uuid.UUID, limit int, offset int) ([]*domain.Message, error) {
	ret := _m.Called(ctx, chatID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByChatID")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.Message, error)); ok {
		return rf(ctx, chatID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.Message); ok {
		r0 = rf(ctx, chatID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, chatID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_GetByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChatID'
type MockMessageRepository_GetByChatID_Call struct {
	*mock.Call
}

// GetByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockMessageRepository_Expecter) GetByChatID(ctx interface{}, chatID interface{}, limit interface{}, offset interface{}) *MockMessageRepository_GetByChatID_Call {
	return &MockMessageRepository_GetByChatID_Call{Call: _e.mock.On("GetByChatID", ctx, chatID, limit, offset)}
}

func (_c *MockMessageRepository_GetByChatID_Call) Run(run func(ctx context.Context, chatID uuid.UUID, limit int, offset int)) *MockMessageRepository_GetByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockMessageRepository_GetByChatID_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageRepository_GetByChatID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_GetByChatID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*domain.Message, error)) *MockMessageRepository_GetByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
